export const actionTypes = {

	CHAT_MESSAGE_BROADCAST: 'CHAT_MESSAGE_BROADCAST',
	CHAT_MESSAGE_WHISPER: 'CHAT_MESSAGE_WHISPER',
	
	USER_JOIN: 'USER_JOIN',
	USER_LEAVE: 'USER_LEAVE',
	USER_UPDATE: 'USER_UPDATE',
	WELCOME: 'WELCOME',

	CLIENT_SET_ALIAS: 'CLIENT_SET_ALIAS',
};